apiVersion : apps/v1
kind: Deployment
metadata:
  name: tushpattpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
        app: tushpattpipelinesjavascriptdocker
    spec:
      containers:
        - name: tushpattpipelinesjavascriptdocker 
          image: mycontainerregistrytushar.azurecr.io/tushpattpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
